/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as BookSlugIndexRouteImport } from './routes/book.$slug.index'
import { Route as BookSlugConfirmRouteImport } from './routes/book.$slug.confirm'
import { Route as BookSlugPaymentRouteImport } from './routes/book.$slug.payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSlugIndexRoute = BookSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookSlugRoute,
} as any)
const BookSlugConfirmRoute = BookSlugConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => BookSlugRoute,
} as any)
const BookSlugPaymentRoute = BookSlugPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => BookSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/book/$slug': typeof BookSlugRouteWithChildren
  '/book/$slug/confirm': typeof BookSlugConfirmRoute
  '/book/$slug/payment': typeof BookSlugPaymentRoute
  '/book/$slug/': typeof BookSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/book/$slug/confirm': typeof BookSlugConfirmRoute
  '/book/$slug/payment': typeof BookSlugPaymentRoute
  '/book/$slug': typeof BookSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/services': typeof ServicesRoute
  '/book/$slug': typeof BookSlugRouteWithChildren
  '/book/$slug/confirm': typeof BookSlugConfirmRoute
  '/book/$slug/payment': typeof BookSlugPaymentRoute
  '/book/$slug/': typeof BookSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/book/$slug'
    | '/book/$slug/confirm'
    | '/book/$slug/payment'
    | '/book/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/book/$slug/confirm'
    | '/book/$slug/payment'
    | '/book/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/services'
    | '/book/$slug'
    | '/book/$slug/confirm'
    | '/book/$slug/payment'
    | '/book/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ServicesRoute: typeof ServicesRoute
  BookSlugRoute: typeof BookSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$slug/': {
      id: '/book/$slug/'
      path: '/'
      fullPath: '/book/$slug/'
      preLoaderRoute: typeof BookSlugIndexRouteImport
      parentRoute: typeof BookSlugRoute
    }
    '/book/$slug/confirm': {
      id: '/book/$slug/confirm'
      path: '/confirm'
      fullPath: '/book/$slug/confirm'
      preLoaderRoute: typeof BookSlugConfirmRouteImport
      parentRoute: typeof BookSlugRoute
    }
    '/book/$slug/payment': {
      id: '/book/$slug/payment'
      path: '/payment'
      fullPath: '/book/$slug/payment'
      preLoaderRoute: typeof BookSlugPaymentRouteImport
      parentRoute: typeof BookSlugRoute
    }
  }
}

interface BookSlugRouteChildren {
  BookSlugConfirmRoute: typeof BookSlugConfirmRoute
  BookSlugPaymentRoute: typeof BookSlugPaymentRoute
  BookSlugIndexRoute: typeof BookSlugIndexRoute
}

const BookSlugRouteChildren: BookSlugRouteChildren = {
  BookSlugConfirmRoute: BookSlugConfirmRoute,
  BookSlugPaymentRoute: BookSlugPaymentRoute,
  BookSlugIndexRoute: BookSlugIndexRoute,
}

const BookSlugRouteWithChildren = BookSlugRoute._addFileChildren(
  BookSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ServicesRoute: ServicesRoute,
  BookSlugRoute: BookSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
